### ISSUE TITLE
칸반 보드 티켓 템플릿 정하기~7.7

### ISSUE THREAD

**Issue by yeonjuan** [wever-ko/README-generator#1]

**Comment by yeonjuan** [comment]
1. 프로젝트 생성시 Automated Kanban 으로 생성시 자동으로 칸반티켓 생성 및 이동 가능
2. 단 이슈 수정/생성시 오른쪽에 Projects에서 `1`에서 설정한 프로젝트로 설정해줘야함.

**Comment by Bumkeyy** [comment]
`In progress` 후에 `validate` step을 추가하는 건 어떰?
각자 해결했다고 생각하면 `In progress`에서 `validate`으로 옮긴 후 
셋이서 회의할때 **`validate` 있는 이슈들만 확인 한 후 `done`으로 옮길지 다시 작업할 지 확인하는 식**
지금은 이슈가 주당 한개지만 나중에 프로젝트가 커지면 여러개가 생길 수 도 있고 ㅎㅎㅎ

**Comment by yeonjuan** [comment]
@Bumkeyy  전원 코드 리뷰를 통해서 Merge 할거라 불필요한 step같음
